version: '3.4'

services:
  jaeger-test:
    image: jaegertracing/all-in-one:1.48
    ports:
      - '16686:16686'
      - '9411:9411'
      - '5778:5778'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '4317:4317'
      - '4318:4318'
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
